# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

schedules:
- cron: "37 21 * * 0"
  displayName: every Sunday, at 21:37
  branches:
    include:
      - master
  always: true


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install python3-venv python3-pygit2
    python3 -m venv venv
    source ./venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install twine
    #python setup.py sdist bdist_wheel
  displayName: 'Set up the env'

- script: |
    source venv/bin/activate
    ./edb2cve.py --reverse --output artifacts/cve-to-edbid-map.json _workdir/exploitdb
  displayName: 'Build the mappings'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/artifacts/cve-to-edbid-map.json'
    artifact: 'edbid-to-cve-map'
    publishLocation: 'pipeline'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'jnahorny'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildId)'
#    tag: '$(Date:yyyyMMdd)$(Rev:.r)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'